import Head from 'next/head'
import React from 'react';
import {  signIn ,useSession, signOut, getSession} from "next-auth/react"
import { useRouter } from "next/router"


export default function Home() {
  const router = useRouter()
  const { data: session } = useSession()
  // const {session} = useSession().data
  console.log(session);

  const signout = () => {
    signOut({ callbackUrl: 'http://localhost:3000/auth' })
    // router.push("/auth")
  }

  return (
    <>
      <Head>
        <title>Penn stack app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-full text-center space-y-2">
        <p>{session ? session?.user.email : "No user"}</p>
        <button onClick={signout}>sign out</button>
        <h1 className='text-2xl '>Lets Cook, this dou, its amazing</h1>
       </main>
    </>
  );
}

export async function getServerSideProps({req}) {
  const session = await getSession({req})
  // const session = await use

  if(!session){
    return {
      redirect:{
        destination:"/auth",
        permanent:false
      }
    }
  }

  return{
    props:{

    }
  }
}
