import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Penn stack app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-full">
        Hello, whats going on, i dont understand, lets build this appThanks for working
      </main>
    </>
  );
}
