import Head from 'next/head'
import React, { useEffect, useMemo, useState } from 'react';

export default function Home() {


  return (
    <>
      <Head>
        <title>Penn stack app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-full text-center space-y-2">
        <h1 className='text-2xl '>Lets Cook, this dou, its amazing</h1>
              </main>
    </>
  );
}



